apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    prometheus: monitored
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: metrics-port
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: LoadBalancer

