apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "buggycpu"
  namespace: "default"
  labels:
    app: "buggycpu"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "buggycpu"
  template:
    metadata:
      labels:
        app: "buggycpu"
    spec:
      containers:
      - name: buggycpu
        image: skrisacr.azurecr.io/buggyapp:v1
        resources:
          limits:
            cpu: "1000m"
          requests:
            cpu: "500m"
            memory: "512Mi"

