apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-on-aks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                      - aks
      tolerations:
        - key: "virtual-kubelet.io/provider"
          operator: "Equal"
          value: "azure"
          effect: "NoSchedule"
      containers:
        - name: springboot-app
          image: skrisacr.azurecr.io/springbootapp:v1
          ports:
            - containerPort: 8881
      imagePullSecrets:
        - name: acr-secret

