apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-on-aci
  labels:
    app: springboot-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: virtual-node-aci-linux
      tolerations:
        - key: "virtual-kubelet.io/provider"
          operator: "Equal"
          value: "azure"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: springboot-app
          image: skrisacr.azurecr.io/springbootapp:v1
          ports:
            - containerPort: 8881
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-lb-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8881
  type: LoadBalancer

