apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-java
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    ##############################################
    # SPRING BOOT LOG INPUT
    ##############################################
    [INPUT]
        Name              tail
        Path              /usr/app/logs/app.log
        Path_Key          log_path
        Tag               springboot-logs
        Refresh_Interval  5
        DB                /usr/app/logs/flb_springboot.db
        DB.Sync           Normal

    [FILTER]
        Name modify
        Match springboot-logs
        Add  app_name springboot-app

    ##############################################
    # OUTPUT TO AZURE LOG ANALYTICS
    ##############################################

    [OUTPUT]
        Name              azure
        Match             springboot-logs
        Customer_ID       ${WORKSPACE_ID}
        Shared_Key        ${SHARED_KEY}
        Log_Type          springbootlogs

