apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-required-affinity
  labels:
    app: springboot-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: teamname
                    operator: In
                    values:
                      - sre
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: springboot-app
      containers:
        - name: springboot-app
          image: sumanth17121988/appjava:1
          ports:
            - name: metrics-port
              containerPort: 8881

