# ❌ Default HPA (averages CPU usage across all containers)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: buggycpu-default-hpa
  labels:
    app: buggycpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buggycpu
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: ContainerResource
      containerResource:
        name: cpu
        container: buggycpu
        target:
          type: Utilization
          averageUtilization: 80


