apiVersion: v1
kind: Pod
metadata:
  name: nginx-app-affinity
spec:
  containers:
  - name: nginx-app
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.azure.com/agentpool
            operator: In
            values:
            - appnode

