apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-recreate-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: springboot-recreate-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: springboot-recreate-app
    spec:
      containers:
        - name: springboot
          image: skrisacr.azurecr.io/springbootapp:v1
          ports:
            - containerPort: 8881
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-recreate-app-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-recreate-app
  ports:
    - port: 8881
      targetPort: 8881
      protocol: TCP

