apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-rollingupdate-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: springboot-rollingupdate-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: springboot-rollingupdate-app
    spec:
      containers:
        - name: springboot
          image: skrisacr.azurecr.io/springbootapp:v1
          ports:
            - containerPort: 8881
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-rollingupdate-app-service
spec:
  type: LoadBalancer
  selector:
    app: springboot-rollingupdate-app
  ports:
    - port: 8881
      targetPort: 8881
      protocol: TCP

