apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info

    ##############################################
    # NGINX LOG INPUT
    ##############################################
    [INPUT]
        Name              tail
        Path              /var/log/nginx/access.log
        Path_Key          log_path
        Tag               nginx-logs
        Refresh_Interval  5
        DB                /var/log/flb_nginx.db
        DB.Sync           Normal

    [FILTER]
        Name modify
        Match nginx-logs
        Add  app_name nginx

    ##############################################
    # SPRING BOOT LOG INPUT (STDOUT via file tail)
    ##############################################
    [INPUT]
        Name              tail
        Path              /usr/app/logs/app.log
        Path_Key          log_path
        Tag               springboot-logs
        Refresh_Interval  5
        DB                /usr/app/logs/flb_springboot.db
        DB.Sync           Normal

    [FILTER]
        Name modify
        Match springboot-logs
        Add  app_name springboot-app

    ##############################################
    # COMMON OUTPUT TO AZURE LOG ANALYTICS
    ##############################################
    [OUTPUT]
        Name              azure
        Match             nginx-logs
        Customer_ID       ${WORKSPACE_ID}
        Shared_Key        ${SHARED_KEY}
        Log_Type          nginxlogs

    [OUTPUT]
        Name              azure
        Match             springboot-logs
        Customer_ID       ${WORKSPACE_ID}
        Shared_Key        ${SHARED_KEY}
        Log_Type          springbootlogs

