apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      nodeSelector:
        agentpool: appnode  # 👈 Ensures pod is scheduled on appnode node pool
      containers:
      - name: springboot-app
        image: sumanth17121988/springbootmetric:1
        ports:
        - containerPort: 8881  # Application port

