apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8881               # Service port
      targetPort: 8881         # Container port
  type: LoadBalancer
