# test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: rbac-test
  namespace: demo-rbac
spec:
  serviceAccountName: testuser
  containers:
  - name: tester
    image: bitnami/kubectl:latest
    command: ["/bin/sh", "-c"]
    args: ["sleep 3600"]

