apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
  labels:
    prometheus: monitored  # Label to match ServiceMonitor (for Prometheus)
spec:
  selector:
    app: springboot-microservice    # ⚠️ This must match pod label exactly
  ports:
    - protocol: TCP
      port: 8881           # Exposed service port
      targetPort: 8881     # Matches container port
  type: ClusterIP      # Exposes this service with a public IP

