# nginx-graceful.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      terminationGracePeriodSeconds: 30  # Wait time before force kill
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "echo Graceful shutdown && sleep 15"]

