apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-avoid-team
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: teamname
                    operator: NotIn
                    values: [sre]
      containers:
        - name: springboot-app
          image: sumanth17121988/appjava:1
          ports:
            - containerPort: 8881

