apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-preferred-affinity
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: env
                    operator: In
                    values: [dev]
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

