apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-required-affinity
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - pre-prod
      containers:
        - name: springboot-app
          image: sumanth17121988/appjava:1
          ports:
            - name: metrics-port
              containerPort: 8881
