apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
spec:
  type: LoadBalancer
  ports:
    - name: metrics-port
      protocol: TCP
      port: 8881
      targetPort: 8881
  selector:
    app: springboot-app

